# Generated by Django 3.2.5 on 2021-07-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('country_or_area', models.CharField(max_length=250)),
                ('value', models.FloatField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
